name: test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - master

jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["latest"]
        typescript: ["5.0", "latest"]
    name: Test with TypeScript ${{ matrix.typescript }} on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: pnpm install
      - run: pnpm add typescript@${{ matrix.typescript }}
      - run: pnpm build
      - run: pnpm test

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["latest"]
    name: Lint on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: pnpm install
      - run: pnpm prettier:check
      - run: pnpm lint:check